# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d876438184159d87d0f12081ee5652fb7be3d46b6f01072c160a8d68ce95707b086865305602f7dd413c500035ad3afc46635fc38a31dd51cc49a50cd1b118ec

test:
  secret_key_base: d5faa40f0c24779e6e82e7b5eba33e6eaf7b7e0e9d4622430ac5bc4571e903b3bb0078c3a255c99de451dc43db0ed6f3a0f89ff07ea4e68c78f08b2202642da6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
